// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OnlineRequestProtocol.proto

package protobuf.dto;

/**
 * <pre>
 * 更换服装
 * </pre>
 *
 * Protobuf type {@code protobuf.dto.OnlineChangeClothesDTO}
 */
public final class OnlineChangeClothesDTO extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protobuf.dto.OnlineChangeClothesDTO)
    OnlineChangeClothesDTOOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OnlineChangeClothesDTO.newBuilder() to construct.
  private OnlineChangeClothesDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OnlineChangeClothesDTO() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OnlineChangeClothesDTO();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OnlineChangeClothesDTO(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            type_ = input.readUInt32();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000001;
            buyClothesType_ = input.readUInt32();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000002;
            buyClothesId_ = input.readUInt32();
            break;
          }
          case 32: {

            hair_ = input.readUInt32();
            break;
          }
          case 40: {

            eye_ = input.readUInt32();
            break;
          }
          case 48: {

            jacket_ = input.readUInt32();
            break;
          }
          case 56: {

            trousers_ = input.readUInt32();
            break;
          }
          case 64: {

            shoes_ = input.readUInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protobuf.dto.OnlineRequest.internal_static_protobuf_dto_OnlineChangeClothesDTO_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protobuf.dto.OnlineRequest.internal_static_protobuf_dto_OnlineChangeClothesDTO_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protobuf.dto.OnlineChangeClothesDTO.class, protobuf.dto.OnlineChangeClothesDTO.Builder.class);
  }

  private int bitField0_;
  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <pre>
   * 消息类型
   * </pre>
   *
   * <code>uint32 type = 1;</code>
   * @return The type.
   */
  @java.lang.Override
  public int getType() {
    return type_;
  }

  public static final int BUY_CLOTHES_TYPE_FIELD_NUMBER = 2;
  private int buyClothesType_;
  /**
   * <pre>
   * 购买服装分类编号
   * </pre>
   *
   * <code>optional uint32 buy_clothes_type = 2;</code>
   * @return Whether the buyClothesType field is set.
   */
  @java.lang.Override
  public boolean hasBuyClothesType() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * 购买服装分类编号
   * </pre>
   *
   * <code>optional uint32 buy_clothes_type = 2;</code>
   * @return The buyClothesType.
   */
  @java.lang.Override
  public int getBuyClothesType() {
    return buyClothesType_;
  }

  public static final int BUY_CLOTHES_ID_FIELD_NUMBER = 3;
  private int buyClothesId_;
  /**
   * <pre>
   * 购买服装编号
   * </pre>
   *
   * <code>optional uint32 buy_clothes_id = 3;</code>
   * @return Whether the buyClothesId field is set.
   */
  @java.lang.Override
  public boolean hasBuyClothesId() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * 购买服装编号
   * </pre>
   *
   * <code>optional uint32 buy_clothes_id = 3;</code>
   * @return The buyClothesId.
   */
  @java.lang.Override
  public int getBuyClothesId() {
    return buyClothesId_;
  }

  public static final int HAIR_FIELD_NUMBER = 4;
  private int hair_;
  /**
   * <pre>
   * 头发
   * </pre>
   *
   * <code>uint32 hair = 4;</code>
   * @return The hair.
   */
  @java.lang.Override
  public int getHair() {
    return hair_;
  }

  public static final int EYE_FIELD_NUMBER = 5;
  private int eye_;
  /**
   * <pre>
   * 眼睛
   * </pre>
   *
   * <code>uint32 eye = 5;</code>
   * @return The eye.
   */
  @java.lang.Override
  public int getEye() {
    return eye_;
  }

  public static final int JACKET_FIELD_NUMBER = 6;
  private int jacket_;
  /**
   * <pre>
   * 上衣
   * </pre>
   *
   * <code>uint32 jacket = 6;</code>
   * @return The jacket.
   */
  @java.lang.Override
  public int getJacket() {
    return jacket_;
  }

  public static final int TROUSERS_FIELD_NUMBER = 7;
  private int trousers_;
  /**
   * <pre>
   * 裤子
   * </pre>
   *
   * <code>uint32 trousers = 7;</code>
   * @return The trousers.
   */
  @java.lang.Override
  public int getTrousers() {
    return trousers_;
  }

  public static final int SHOES_FIELD_NUMBER = 8;
  private int shoes_;
  /**
   * <pre>
   * 鞋子
   * </pre>
   *
   * <code>uint32 shoes = 8;</code>
   * @return The shoes.
   */
  @java.lang.Override
  public int getShoes() {
    return shoes_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != 0) {
      output.writeUInt32(1, type_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeUInt32(2, buyClothesType_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeUInt32(3, buyClothesId_);
    }
    if (hair_ != 0) {
      output.writeUInt32(4, hair_);
    }
    if (eye_ != 0) {
      output.writeUInt32(5, eye_);
    }
    if (jacket_ != 0) {
      output.writeUInt32(6, jacket_);
    }
    if (trousers_ != 0) {
      output.writeUInt32(7, trousers_);
    }
    if (shoes_ != 0) {
      output.writeUInt32(8, shoes_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, type_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, buyClothesType_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, buyClothesId_);
    }
    if (hair_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, hair_);
    }
    if (eye_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, eye_);
    }
    if (jacket_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(6, jacket_);
    }
    if (trousers_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(7, trousers_);
    }
    if (shoes_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(8, shoes_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protobuf.dto.OnlineChangeClothesDTO)) {
      return super.equals(obj);
    }
    protobuf.dto.OnlineChangeClothesDTO other = (protobuf.dto.OnlineChangeClothesDTO) obj;

    if (getType()
        != other.getType()) return false;
    if (hasBuyClothesType() != other.hasBuyClothesType()) return false;
    if (hasBuyClothesType()) {
      if (getBuyClothesType()
          != other.getBuyClothesType()) return false;
    }
    if (hasBuyClothesId() != other.hasBuyClothesId()) return false;
    if (hasBuyClothesId()) {
      if (getBuyClothesId()
          != other.getBuyClothesId()) return false;
    }
    if (getHair()
        != other.getHair()) return false;
    if (getEye()
        != other.getEye()) return false;
    if (getJacket()
        != other.getJacket()) return false;
    if (getTrousers()
        != other.getTrousers()) return false;
    if (getShoes()
        != other.getShoes()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType();
    if (hasBuyClothesType()) {
      hash = (37 * hash) + BUY_CLOTHES_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getBuyClothesType();
    }
    if (hasBuyClothesId()) {
      hash = (37 * hash) + BUY_CLOTHES_ID_FIELD_NUMBER;
      hash = (53 * hash) + getBuyClothesId();
    }
    hash = (37 * hash) + HAIR_FIELD_NUMBER;
    hash = (53 * hash) + getHair();
    hash = (37 * hash) + EYE_FIELD_NUMBER;
    hash = (53 * hash) + getEye();
    hash = (37 * hash) + JACKET_FIELD_NUMBER;
    hash = (53 * hash) + getJacket();
    hash = (37 * hash) + TROUSERS_FIELD_NUMBER;
    hash = (53 * hash) + getTrousers();
    hash = (37 * hash) + SHOES_FIELD_NUMBER;
    hash = (53 * hash) + getShoes();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protobuf.dto.OnlineChangeClothesDTO parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.dto.OnlineChangeClothesDTO parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.dto.OnlineChangeClothesDTO parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.dto.OnlineChangeClothesDTO parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.dto.OnlineChangeClothesDTO parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.dto.OnlineChangeClothesDTO parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.dto.OnlineChangeClothesDTO parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuf.dto.OnlineChangeClothesDTO parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuf.dto.OnlineChangeClothesDTO parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protobuf.dto.OnlineChangeClothesDTO parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuf.dto.OnlineChangeClothesDTO parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuf.dto.OnlineChangeClothesDTO parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protobuf.dto.OnlineChangeClothesDTO prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 更换服装
   * </pre>
   *
   * Protobuf type {@code protobuf.dto.OnlineChangeClothesDTO}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protobuf.dto.OnlineChangeClothesDTO)
      protobuf.dto.OnlineChangeClothesDTOOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.dto.OnlineRequest.internal_static_protobuf_dto_OnlineChangeClothesDTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.dto.OnlineRequest.internal_static_protobuf_dto_OnlineChangeClothesDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.dto.OnlineChangeClothesDTO.class, protobuf.dto.OnlineChangeClothesDTO.Builder.class);
    }

    // Construct using protobuf.dto.OnlineChangeClothesDTO.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      type_ = 0;

      buyClothesType_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      buyClothesId_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      hair_ = 0;

      eye_ = 0;

      jacket_ = 0;

      trousers_ = 0;

      shoes_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protobuf.dto.OnlineRequest.internal_static_protobuf_dto_OnlineChangeClothesDTO_descriptor;
    }

    @java.lang.Override
    public protobuf.dto.OnlineChangeClothesDTO getDefaultInstanceForType() {
      return protobuf.dto.OnlineChangeClothesDTO.getDefaultInstance();
    }

    @java.lang.Override
    public protobuf.dto.OnlineChangeClothesDTO build() {
      protobuf.dto.OnlineChangeClothesDTO result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protobuf.dto.OnlineChangeClothesDTO buildPartial() {
      protobuf.dto.OnlineChangeClothesDTO result = new protobuf.dto.OnlineChangeClothesDTO(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.type_ = type_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.buyClothesType_ = buyClothesType_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.buyClothesId_ = buyClothesId_;
        to_bitField0_ |= 0x00000002;
      }
      result.hair_ = hair_;
      result.eye_ = eye_;
      result.jacket_ = jacket_;
      result.trousers_ = trousers_;
      result.shoes_ = shoes_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protobuf.dto.OnlineChangeClothesDTO) {
        return mergeFrom((protobuf.dto.OnlineChangeClothesDTO)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protobuf.dto.OnlineChangeClothesDTO other) {
      if (other == protobuf.dto.OnlineChangeClothesDTO.getDefaultInstance()) return this;
      if (other.getType() != 0) {
        setType(other.getType());
      }
      if (other.hasBuyClothesType()) {
        setBuyClothesType(other.getBuyClothesType());
      }
      if (other.hasBuyClothesId()) {
        setBuyClothesId(other.getBuyClothesId());
      }
      if (other.getHair() != 0) {
        setHair(other.getHair());
      }
      if (other.getEye() != 0) {
        setEye(other.getEye());
      }
      if (other.getJacket() != 0) {
        setJacket(other.getJacket());
      }
      if (other.getTrousers() != 0) {
        setTrousers(other.getTrousers());
      }
      if (other.getShoes() != 0) {
        setShoes(other.getShoes());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protobuf.dto.OnlineChangeClothesDTO parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protobuf.dto.OnlineChangeClothesDTO) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int type_ ;
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>uint32 type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>uint32 type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(int value) {
      
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>uint32 type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private int buyClothesType_ ;
    /**
     * <pre>
     * 购买服装分类编号
     * </pre>
     *
     * <code>optional uint32 buy_clothes_type = 2;</code>
     * @return Whether the buyClothesType field is set.
     */
    @java.lang.Override
    public boolean hasBuyClothesType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * 购买服装分类编号
     * </pre>
     *
     * <code>optional uint32 buy_clothes_type = 2;</code>
     * @return The buyClothesType.
     */
    @java.lang.Override
    public int getBuyClothesType() {
      return buyClothesType_;
    }
    /**
     * <pre>
     * 购买服装分类编号
     * </pre>
     *
     * <code>optional uint32 buy_clothes_type = 2;</code>
     * @param value The buyClothesType to set.
     * @return This builder for chaining.
     */
    public Builder setBuyClothesType(int value) {
      bitField0_ |= 0x00000001;
      buyClothesType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 购买服装分类编号
     * </pre>
     *
     * <code>optional uint32 buy_clothes_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBuyClothesType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      buyClothesType_ = 0;
      onChanged();
      return this;
    }

    private int buyClothesId_ ;
    /**
     * <pre>
     * 购买服装编号
     * </pre>
     *
     * <code>optional uint32 buy_clothes_id = 3;</code>
     * @return Whether the buyClothesId field is set.
     */
    @java.lang.Override
    public boolean hasBuyClothesId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * 购买服装编号
     * </pre>
     *
     * <code>optional uint32 buy_clothes_id = 3;</code>
     * @return The buyClothesId.
     */
    @java.lang.Override
    public int getBuyClothesId() {
      return buyClothesId_;
    }
    /**
     * <pre>
     * 购买服装编号
     * </pre>
     *
     * <code>optional uint32 buy_clothes_id = 3;</code>
     * @param value The buyClothesId to set.
     * @return This builder for chaining.
     */
    public Builder setBuyClothesId(int value) {
      bitField0_ |= 0x00000002;
      buyClothesId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 购买服装编号
     * </pre>
     *
     * <code>optional uint32 buy_clothes_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBuyClothesId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      buyClothesId_ = 0;
      onChanged();
      return this;
    }

    private int hair_ ;
    /**
     * <pre>
     * 头发
     * </pre>
     *
     * <code>uint32 hair = 4;</code>
     * @return The hair.
     */
    @java.lang.Override
    public int getHair() {
      return hair_;
    }
    /**
     * <pre>
     * 头发
     * </pre>
     *
     * <code>uint32 hair = 4;</code>
     * @param value The hair to set.
     * @return This builder for chaining.
     */
    public Builder setHair(int value) {
      
      hair_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 头发
     * </pre>
     *
     * <code>uint32 hair = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearHair() {
      
      hair_ = 0;
      onChanged();
      return this;
    }

    private int eye_ ;
    /**
     * <pre>
     * 眼睛
     * </pre>
     *
     * <code>uint32 eye = 5;</code>
     * @return The eye.
     */
    @java.lang.Override
    public int getEye() {
      return eye_;
    }
    /**
     * <pre>
     * 眼睛
     * </pre>
     *
     * <code>uint32 eye = 5;</code>
     * @param value The eye to set.
     * @return This builder for chaining.
     */
    public Builder setEye(int value) {
      
      eye_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 眼睛
     * </pre>
     *
     * <code>uint32 eye = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearEye() {
      
      eye_ = 0;
      onChanged();
      return this;
    }

    private int jacket_ ;
    /**
     * <pre>
     * 上衣
     * </pre>
     *
     * <code>uint32 jacket = 6;</code>
     * @return The jacket.
     */
    @java.lang.Override
    public int getJacket() {
      return jacket_;
    }
    /**
     * <pre>
     * 上衣
     * </pre>
     *
     * <code>uint32 jacket = 6;</code>
     * @param value The jacket to set.
     * @return This builder for chaining.
     */
    public Builder setJacket(int value) {
      
      jacket_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 上衣
     * </pre>
     *
     * <code>uint32 jacket = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearJacket() {
      
      jacket_ = 0;
      onChanged();
      return this;
    }

    private int trousers_ ;
    /**
     * <pre>
     * 裤子
     * </pre>
     *
     * <code>uint32 trousers = 7;</code>
     * @return The trousers.
     */
    @java.lang.Override
    public int getTrousers() {
      return trousers_;
    }
    /**
     * <pre>
     * 裤子
     * </pre>
     *
     * <code>uint32 trousers = 7;</code>
     * @param value The trousers to set.
     * @return This builder for chaining.
     */
    public Builder setTrousers(int value) {
      
      trousers_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 裤子
     * </pre>
     *
     * <code>uint32 trousers = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTrousers() {
      
      trousers_ = 0;
      onChanged();
      return this;
    }

    private int shoes_ ;
    /**
     * <pre>
     * 鞋子
     * </pre>
     *
     * <code>uint32 shoes = 8;</code>
     * @return The shoes.
     */
    @java.lang.Override
    public int getShoes() {
      return shoes_;
    }
    /**
     * <pre>
     * 鞋子
     * </pre>
     *
     * <code>uint32 shoes = 8;</code>
     * @param value The shoes to set.
     * @return This builder for chaining.
     */
    public Builder setShoes(int value) {
      
      shoes_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 鞋子
     * </pre>
     *
     * <code>uint32 shoes = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearShoes() {
      
      shoes_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protobuf.dto.OnlineChangeClothesDTO)
  }

  // @@protoc_insertion_point(class_scope:protobuf.dto.OnlineChangeClothesDTO)
  private static final protobuf.dto.OnlineChangeClothesDTO DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protobuf.dto.OnlineChangeClothesDTO();
  }

  public static protobuf.dto.OnlineChangeClothesDTO getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OnlineChangeClothesDTO>
      PARSER = new com.google.protobuf.AbstractParser<OnlineChangeClothesDTO>() {
    @java.lang.Override
    public OnlineChangeClothesDTO parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OnlineChangeClothesDTO(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OnlineChangeClothesDTO> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OnlineChangeClothesDTO> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protobuf.dto.OnlineChangeClothesDTO getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

