// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OnlineResponseProtocol.proto

package ly.pp.justpiano3.protobuf.vo;

public interface OnlineLoadRoomListVOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ly.pp.justpiano3.protobuf.vo.OnlineLoadRoomListVO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 房间列表
   * </pre>
   *
   * <code>repeated .ly.pp.justpiano3.protobuf.vo.OnlineRoomVO room = 1;</code>
   */
  java.util.List<ly.pp.justpiano3.protobuf.vo.OnlineRoomVO> 
      getRoomList();
  /**
   * <pre>
   * 房间列表
   * </pre>
   *
   * <code>repeated .ly.pp.justpiano3.protobuf.vo.OnlineRoomVO room = 1;</code>
   */
  ly.pp.justpiano3.protobuf.vo.OnlineRoomVO getRoom(int index);
  /**
   * <pre>
   * 房间列表
   * </pre>
   *
   * <code>repeated .ly.pp.justpiano3.protobuf.vo.OnlineRoomVO room = 1;</code>
   */
  int getRoomCount();
  /**
   * <pre>
   * 房间列表
   * </pre>
   *
   * <code>repeated .ly.pp.justpiano3.protobuf.vo.OnlineRoomVO room = 1;</code>
   */
  java.util.List<? extends ly.pp.justpiano3.protobuf.vo.OnlineRoomVOOrBuilder> 
      getRoomOrBuilderList();
  /**
   * <pre>
   * 房间列表
   * </pre>
   *
   * <code>repeated .ly.pp.justpiano3.protobuf.vo.OnlineRoomVO room = 1;</code>
   */
  ly.pp.justpiano3.protobuf.vo.OnlineRoomVOOrBuilder getRoomOrBuilder(
      int index);
}
