// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OnlineResponseProtocol.proto

package ly.pp.justpiano3.protobuf.vo;

public interface OnlineFamilyCreateVOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ly.pp.justpiano3.protobuf.vo.OnlineFamilyCreateVO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 创建家族结果
   * </pre>
   *
   * <code>uint32 result = 1;</code>
   * @return The result.
   */
  int getResult();
}
