// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OnlineResponseProtocol.proto

package ly.pp.justpiano3.protobuf.vo;

/**
 * <pre>
 * 查看用户个人资料对话框
 * </pre>
 *
 * Protobuf type {@code ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO}
 */
public final class OnlineUserInfoDialogVO extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO)
    OnlineUserInfoDialogVOOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OnlineUserInfoDialogVO.newBuilder() to construct.
  private OnlineUserInfoDialogVO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OnlineUserInfoDialogVO() {
    name_ = "";
    family_ = "";
    signature_ = "";
    gender_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OnlineUserInfoDialogVO();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OnlineUserInfoDialogVO(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 16: {

            lv_ = input.readUInt32();
            break;
          }
          case 24: {

            exp_ = input.readUInt32();
            break;
          }
          case 32: {

            cl_ = input.readUInt32();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            family_ = s;
            break;
          }
          case 50: {
            ly.pp.justpiano3.protobuf.vo.OnlineClothesVO.Builder subBuilder = null;
            if (clothes_ != null) {
              subBuilder = clothes_.toBuilder();
            }
            clothes_ = input.readMessage(ly.pp.justpiano3.protobuf.vo.OnlineClothesVO.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(clothes_);
              clothes_ = subBuilder.buildPartial();
            }

            break;
          }
          case 56: {

            winnerNum_ = input.readUInt32();
            break;
          }
          case 64: {

            score_ = input.readUInt32();
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            signature_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            gender_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ly.pp.justpiano3.protobuf.vo.OnlineResponse.internal_static_ly_pp_justpiano3_protobuf_vo_OnlineUserInfoDialogVO_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ly.pp.justpiano3.protobuf.vo.OnlineResponse.internal_static_ly_pp_justpiano3_protobuf_vo_OnlineUserInfoDialogVO_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO.class, ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   * 用户名称
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 用户名称
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LV_FIELD_NUMBER = 2;
  private int lv_;
  /**
   * <pre>
   * 用户等级
   * </pre>
   *
   * <code>uint32 lv = 2;</code>
   * @return The lv.
   */
  @java.lang.Override
  public int getLv() {
    return lv_;
  }

  public static final int EXP_FIELD_NUMBER = 3;
  private int exp_;
  /**
   * <pre>
   * 用户经验
   * </pre>
   *
   * <code>uint32 exp = 3;</code>
   * @return The exp.
   */
  @java.lang.Override
  public int getExp() {
    return exp_;
  }

  public static final int CL_FIELD_NUMBER = 4;
  private int cl_;
  /**
   * <pre>
   * 用户考级
   * </pre>
   *
   * <code>uint32 cl = 4;</code>
   * @return The cl.
   */
  @java.lang.Override
  public int getCl() {
    return cl_;
  }

  public static final int FAMILY_FIELD_NUMBER = 5;
  private volatile java.lang.Object family_;
  /**
   * <pre>
   * 用户所在家族名称及职位
   * </pre>
   *
   * <code>string family = 5;</code>
   * @return The family.
   */
  @java.lang.Override
  public java.lang.String getFamily() {
    java.lang.Object ref = family_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      family_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 用户所在家族名称及职位
   * </pre>
   *
   * <code>string family = 5;</code>
   * @return The bytes for family.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFamilyBytes() {
    java.lang.Object ref = family_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      family_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLOTHES_FIELD_NUMBER = 6;
  private ly.pp.justpiano3.protobuf.vo.OnlineClothesVO clothes_;
  /**
   * <pre>
   * 用户服装
   * </pre>
   *
   * <code>.ly.pp.justpiano3.protobuf.vo.OnlineClothesVO clothes = 6;</code>
   * @return Whether the clothes field is set.
   */
  @java.lang.Override
  public boolean hasClothes() {
    return clothes_ != null;
  }
  /**
   * <pre>
   * 用户服装
   * </pre>
   *
   * <code>.ly.pp.justpiano3.protobuf.vo.OnlineClothesVO clothes = 6;</code>
   * @return The clothes.
   */
  @java.lang.Override
  public ly.pp.justpiano3.protobuf.vo.OnlineClothesVO getClothes() {
    return clothes_ == null ? ly.pp.justpiano3.protobuf.vo.OnlineClothesVO.getDefaultInstance() : clothes_;
  }
  /**
   * <pre>
   * 用户服装
   * </pre>
   *
   * <code>.ly.pp.justpiano3.protobuf.vo.OnlineClothesVO clothes = 6;</code>
   */
  @java.lang.Override
  public ly.pp.justpiano3.protobuf.vo.OnlineClothesVOOrBuilder getClothesOrBuilder() {
    return getClothes();
  }

  public static final int WINNER_NUM_FIELD_NUMBER = 7;
  private int winnerNum_;
  /**
   * <pre>
   * 用户冠军数量
   * </pre>
   *
   * <code>uint32 winner_num = 7;</code>
   * @return The winnerNum.
   */
  @java.lang.Override
  public int getWinnerNum() {
    return winnerNum_;
  }

  public static final int SCORE_FIELD_NUMBER = 8;
  private int score_;
  /**
   * <pre>
   * 用户在线曲库总分
   * </pre>
   *
   * <code>uint32 score = 8;</code>
   * @return The score.
   */
  @java.lang.Override
  public int getScore() {
    return score_;
  }

  public static final int SIGNATURE_FIELD_NUMBER = 9;
  private volatile java.lang.Object signature_;
  /**
   * <pre>
   * 用户个性签名
   * </pre>
   *
   * <code>string signature = 9;</code>
   * @return The signature.
   */
  @java.lang.Override
  public java.lang.String getSignature() {
    java.lang.Object ref = signature_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      signature_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 用户个性签名
   * </pre>
   *
   * <code>string signature = 9;</code>
   * @return The bytes for signature.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSignatureBytes() {
    java.lang.Object ref = signature_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      signature_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GENDER_FIELD_NUMBER = 10;
  private volatile java.lang.Object gender_;
  /**
   * <pre>
   * 用户性别
   * </pre>
   *
   * <code>string gender = 10;</code>
   * @return The gender.
   */
  @java.lang.Override
  public java.lang.String getGender() {
    java.lang.Object ref = gender_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      gender_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 用户性别
   * </pre>
   *
   * <code>string gender = 10;</code>
   * @return The bytes for gender.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGenderBytes() {
    java.lang.Object ref = gender_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gender_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (lv_ != 0) {
      output.writeUInt32(2, lv_);
    }
    if (exp_ != 0) {
      output.writeUInt32(3, exp_);
    }
    if (cl_ != 0) {
      output.writeUInt32(4, cl_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(family_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, family_);
    }
    if (clothes_ != null) {
      output.writeMessage(6, getClothes());
    }
    if (winnerNum_ != 0) {
      output.writeUInt32(7, winnerNum_);
    }
    if (score_ != 0) {
      output.writeUInt32(8, score_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(signature_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, signature_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(gender_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, gender_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (lv_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, lv_);
    }
    if (exp_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, exp_);
    }
    if (cl_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, cl_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(family_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, family_);
    }
    if (clothes_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getClothes());
    }
    if (winnerNum_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(7, winnerNum_);
    }
    if (score_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(8, score_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(signature_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, signature_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(gender_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, gender_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO)) {
      return super.equals(obj);
    }
    ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO other = (ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (getLv()
        != other.getLv()) return false;
    if (getExp()
        != other.getExp()) return false;
    if (getCl()
        != other.getCl()) return false;
    if (!getFamily()
        .equals(other.getFamily())) return false;
    if (hasClothes() != other.hasClothes()) return false;
    if (hasClothes()) {
      if (!getClothes()
          .equals(other.getClothes())) return false;
    }
    if (getWinnerNum()
        != other.getWinnerNum()) return false;
    if (getScore()
        != other.getScore()) return false;
    if (!getSignature()
        .equals(other.getSignature())) return false;
    if (!getGender()
        .equals(other.getGender())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + LV_FIELD_NUMBER;
    hash = (53 * hash) + getLv();
    hash = (37 * hash) + EXP_FIELD_NUMBER;
    hash = (53 * hash) + getExp();
    hash = (37 * hash) + CL_FIELD_NUMBER;
    hash = (53 * hash) + getCl();
    hash = (37 * hash) + FAMILY_FIELD_NUMBER;
    hash = (53 * hash) + getFamily().hashCode();
    if (hasClothes()) {
      hash = (37 * hash) + CLOTHES_FIELD_NUMBER;
      hash = (53 * hash) + getClothes().hashCode();
    }
    hash = (37 * hash) + WINNER_NUM_FIELD_NUMBER;
    hash = (53 * hash) + getWinnerNum();
    hash = (37 * hash) + SCORE_FIELD_NUMBER;
    hash = (53 * hash) + getScore();
    hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
    hash = (53 * hash) + getSignature().hashCode();
    hash = (37 * hash) + GENDER_FIELD_NUMBER;
    hash = (53 * hash) + getGender().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 查看用户个人资料对话框
   * </pre>
   *
   * Protobuf type {@code ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO)
      ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVOOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ly.pp.justpiano3.protobuf.vo.OnlineResponse.internal_static_ly_pp_justpiano3_protobuf_vo_OnlineUserInfoDialogVO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ly.pp.justpiano3.protobuf.vo.OnlineResponse.internal_static_ly_pp_justpiano3_protobuf_vo_OnlineUserInfoDialogVO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO.class, ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO.Builder.class);
    }

    // Construct using ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      lv_ = 0;

      exp_ = 0;

      cl_ = 0;

      family_ = "";

      if (clothesBuilder_ == null) {
        clothes_ = null;
      } else {
        clothes_ = null;
        clothesBuilder_ = null;
      }
      winnerNum_ = 0;

      score_ = 0;

      signature_ = "";

      gender_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ly.pp.justpiano3.protobuf.vo.OnlineResponse.internal_static_ly_pp_justpiano3_protobuf_vo_OnlineUserInfoDialogVO_descriptor;
    }

    @java.lang.Override
    public ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO getDefaultInstanceForType() {
      return ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO.getDefaultInstance();
    }

    @java.lang.Override
    public ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO build() {
      ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO buildPartial() {
      ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO result = new ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO(this);
      result.name_ = name_;
      result.lv_ = lv_;
      result.exp_ = exp_;
      result.cl_ = cl_;
      result.family_ = family_;
      if (clothesBuilder_ == null) {
        result.clothes_ = clothes_;
      } else {
        result.clothes_ = clothesBuilder_.build();
      }
      result.winnerNum_ = winnerNum_;
      result.score_ = score_;
      result.signature_ = signature_;
      result.gender_ = gender_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO) {
        return mergeFrom((ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO other) {
      if (other == ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.getLv() != 0) {
        setLv(other.getLv());
      }
      if (other.getExp() != 0) {
        setExp(other.getExp());
      }
      if (other.getCl() != 0) {
        setCl(other.getCl());
      }
      if (!other.getFamily().isEmpty()) {
        family_ = other.family_;
        onChanged();
      }
      if (other.hasClothes()) {
        mergeClothes(other.getClothes());
      }
      if (other.getWinnerNum() != 0) {
        setWinnerNum(other.getWinnerNum());
      }
      if (other.getScore() != 0) {
        setScore(other.getScore());
      }
      if (!other.getSignature().isEmpty()) {
        signature_ = other.signature_;
        onChanged();
      }
      if (!other.getGender().isEmpty()) {
        gender_ = other.gender_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * 用户名称
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 用户名称
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 用户名称
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户名称
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户名称
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private int lv_ ;
    /**
     * <pre>
     * 用户等级
     * </pre>
     *
     * <code>uint32 lv = 2;</code>
     * @return The lv.
     */
    @java.lang.Override
    public int getLv() {
      return lv_;
    }
    /**
     * <pre>
     * 用户等级
     * </pre>
     *
     * <code>uint32 lv = 2;</code>
     * @param value The lv to set.
     * @return This builder for chaining.
     */
    public Builder setLv(int value) {
      
      lv_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户等级
     * </pre>
     *
     * <code>uint32 lv = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLv() {
      
      lv_ = 0;
      onChanged();
      return this;
    }

    private int exp_ ;
    /**
     * <pre>
     * 用户经验
     * </pre>
     *
     * <code>uint32 exp = 3;</code>
     * @return The exp.
     */
    @java.lang.Override
    public int getExp() {
      return exp_;
    }
    /**
     * <pre>
     * 用户经验
     * </pre>
     *
     * <code>uint32 exp = 3;</code>
     * @param value The exp to set.
     * @return This builder for chaining.
     */
    public Builder setExp(int value) {
      
      exp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户经验
     * </pre>
     *
     * <code>uint32 exp = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearExp() {
      
      exp_ = 0;
      onChanged();
      return this;
    }

    private int cl_ ;
    /**
     * <pre>
     * 用户考级
     * </pre>
     *
     * <code>uint32 cl = 4;</code>
     * @return The cl.
     */
    @java.lang.Override
    public int getCl() {
      return cl_;
    }
    /**
     * <pre>
     * 用户考级
     * </pre>
     *
     * <code>uint32 cl = 4;</code>
     * @param value The cl to set.
     * @return This builder for chaining.
     */
    public Builder setCl(int value) {
      
      cl_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户考级
     * </pre>
     *
     * <code>uint32 cl = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCl() {
      
      cl_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object family_ = "";
    /**
     * <pre>
     * 用户所在家族名称及职位
     * </pre>
     *
     * <code>string family = 5;</code>
     * @return The family.
     */
    public java.lang.String getFamily() {
      java.lang.Object ref = family_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        family_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 用户所在家族名称及职位
     * </pre>
     *
     * <code>string family = 5;</code>
     * @return The bytes for family.
     */
    public com.google.protobuf.ByteString
        getFamilyBytes() {
      java.lang.Object ref = family_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        family_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 用户所在家族名称及职位
     * </pre>
     *
     * <code>string family = 5;</code>
     * @param value The family to set.
     * @return This builder for chaining.
     */
    public Builder setFamily(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      family_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户所在家族名称及职位
     * </pre>
     *
     * <code>string family = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearFamily() {
      
      family_ = getDefaultInstance().getFamily();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户所在家族名称及职位
     * </pre>
     *
     * <code>string family = 5;</code>
     * @param value The bytes for family to set.
     * @return This builder for chaining.
     */
    public Builder setFamilyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      family_ = value;
      onChanged();
      return this;
    }

    private ly.pp.justpiano3.protobuf.vo.OnlineClothesVO clothes_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ly.pp.justpiano3.protobuf.vo.OnlineClothesVO, ly.pp.justpiano3.protobuf.vo.OnlineClothesVO.Builder, ly.pp.justpiano3.protobuf.vo.OnlineClothesVOOrBuilder> clothesBuilder_;
    /**
     * <pre>
     * 用户服装
     * </pre>
     *
     * <code>.ly.pp.justpiano3.protobuf.vo.OnlineClothesVO clothes = 6;</code>
     * @return Whether the clothes field is set.
     */
    public boolean hasClothes() {
      return clothesBuilder_ != null || clothes_ != null;
    }
    /**
     * <pre>
     * 用户服装
     * </pre>
     *
     * <code>.ly.pp.justpiano3.protobuf.vo.OnlineClothesVO clothes = 6;</code>
     * @return The clothes.
     */
    public ly.pp.justpiano3.protobuf.vo.OnlineClothesVO getClothes() {
      if (clothesBuilder_ == null) {
        return clothes_ == null ? ly.pp.justpiano3.protobuf.vo.OnlineClothesVO.getDefaultInstance() : clothes_;
      } else {
        return clothesBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 用户服装
     * </pre>
     *
     * <code>.ly.pp.justpiano3.protobuf.vo.OnlineClothesVO clothes = 6;</code>
     */
    public Builder setClothes(ly.pp.justpiano3.protobuf.vo.OnlineClothesVO value) {
      if (clothesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        clothes_ = value;
        onChanged();
      } else {
        clothesBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 用户服装
     * </pre>
     *
     * <code>.ly.pp.justpiano3.protobuf.vo.OnlineClothesVO clothes = 6;</code>
     */
    public Builder setClothes(
        ly.pp.justpiano3.protobuf.vo.OnlineClothesVO.Builder builderForValue) {
      if (clothesBuilder_ == null) {
        clothes_ = builderForValue.build();
        onChanged();
      } else {
        clothesBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 用户服装
     * </pre>
     *
     * <code>.ly.pp.justpiano3.protobuf.vo.OnlineClothesVO clothes = 6;</code>
     */
    public Builder mergeClothes(ly.pp.justpiano3.protobuf.vo.OnlineClothesVO value) {
      if (clothesBuilder_ == null) {
        if (clothes_ != null) {
          clothes_ =
            ly.pp.justpiano3.protobuf.vo.OnlineClothesVO.newBuilder(clothes_).mergeFrom(value).buildPartial();
        } else {
          clothes_ = value;
        }
        onChanged();
      } else {
        clothesBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 用户服装
     * </pre>
     *
     * <code>.ly.pp.justpiano3.protobuf.vo.OnlineClothesVO clothes = 6;</code>
     */
    public Builder clearClothes() {
      if (clothesBuilder_ == null) {
        clothes_ = null;
        onChanged();
      } else {
        clothes_ = null;
        clothesBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 用户服装
     * </pre>
     *
     * <code>.ly.pp.justpiano3.protobuf.vo.OnlineClothesVO clothes = 6;</code>
     */
    public ly.pp.justpiano3.protobuf.vo.OnlineClothesVO.Builder getClothesBuilder() {
      
      onChanged();
      return getClothesFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 用户服装
     * </pre>
     *
     * <code>.ly.pp.justpiano3.protobuf.vo.OnlineClothesVO clothes = 6;</code>
     */
    public ly.pp.justpiano3.protobuf.vo.OnlineClothesVOOrBuilder getClothesOrBuilder() {
      if (clothesBuilder_ != null) {
        return clothesBuilder_.getMessageOrBuilder();
      } else {
        return clothes_ == null ?
            ly.pp.justpiano3.protobuf.vo.OnlineClothesVO.getDefaultInstance() : clothes_;
      }
    }
    /**
     * <pre>
     * 用户服装
     * </pre>
     *
     * <code>.ly.pp.justpiano3.protobuf.vo.OnlineClothesVO clothes = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ly.pp.justpiano3.protobuf.vo.OnlineClothesVO, ly.pp.justpiano3.protobuf.vo.OnlineClothesVO.Builder, ly.pp.justpiano3.protobuf.vo.OnlineClothesVOOrBuilder> 
        getClothesFieldBuilder() {
      if (clothesBuilder_ == null) {
        clothesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ly.pp.justpiano3.protobuf.vo.OnlineClothesVO, ly.pp.justpiano3.protobuf.vo.OnlineClothesVO.Builder, ly.pp.justpiano3.protobuf.vo.OnlineClothesVOOrBuilder>(
                getClothes(),
                getParentForChildren(),
                isClean());
        clothes_ = null;
      }
      return clothesBuilder_;
    }

    private int winnerNum_ ;
    /**
     * <pre>
     * 用户冠军数量
     * </pre>
     *
     * <code>uint32 winner_num = 7;</code>
     * @return The winnerNum.
     */
    @java.lang.Override
    public int getWinnerNum() {
      return winnerNum_;
    }
    /**
     * <pre>
     * 用户冠军数量
     * </pre>
     *
     * <code>uint32 winner_num = 7;</code>
     * @param value The winnerNum to set.
     * @return This builder for chaining.
     */
    public Builder setWinnerNum(int value) {
      
      winnerNum_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户冠军数量
     * </pre>
     *
     * <code>uint32 winner_num = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearWinnerNum() {
      
      winnerNum_ = 0;
      onChanged();
      return this;
    }

    private int score_ ;
    /**
     * <pre>
     * 用户在线曲库总分
     * </pre>
     *
     * <code>uint32 score = 8;</code>
     * @return The score.
     */
    @java.lang.Override
    public int getScore() {
      return score_;
    }
    /**
     * <pre>
     * 用户在线曲库总分
     * </pre>
     *
     * <code>uint32 score = 8;</code>
     * @param value The score to set.
     * @return This builder for chaining.
     */
    public Builder setScore(int value) {
      
      score_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户在线曲库总分
     * </pre>
     *
     * <code>uint32 score = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearScore() {
      
      score_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object signature_ = "";
    /**
     * <pre>
     * 用户个性签名
     * </pre>
     *
     * <code>string signature = 9;</code>
     * @return The signature.
     */
    public java.lang.String getSignature() {
      java.lang.Object ref = signature_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        signature_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 用户个性签名
     * </pre>
     *
     * <code>string signature = 9;</code>
     * @return The bytes for signature.
     */
    public com.google.protobuf.ByteString
        getSignatureBytes() {
      java.lang.Object ref = signature_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        signature_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 用户个性签名
     * </pre>
     *
     * <code>string signature = 9;</code>
     * @param value The signature to set.
     * @return This builder for chaining.
     */
    public Builder setSignature(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      signature_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户个性签名
     * </pre>
     *
     * <code>string signature = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearSignature() {
      
      signature_ = getDefaultInstance().getSignature();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户个性签名
     * </pre>
     *
     * <code>string signature = 9;</code>
     * @param value The bytes for signature to set.
     * @return This builder for chaining.
     */
    public Builder setSignatureBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      signature_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object gender_ = "";
    /**
     * <pre>
     * 用户性别
     * </pre>
     *
     * <code>string gender = 10;</code>
     * @return The gender.
     */
    public java.lang.String getGender() {
      java.lang.Object ref = gender_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gender_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 用户性别
     * </pre>
     *
     * <code>string gender = 10;</code>
     * @return The bytes for gender.
     */
    public com.google.protobuf.ByteString
        getGenderBytes() {
      java.lang.Object ref = gender_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 用户性别
     * </pre>
     *
     * <code>string gender = 10;</code>
     * @param value The gender to set.
     * @return This builder for chaining.
     */
    public Builder setGender(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      gender_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户性别
     * </pre>
     *
     * <code>string gender = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearGender() {
      
      gender_ = getDefaultInstance().getGender();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户性别
     * </pre>
     *
     * <code>string gender = 10;</code>
     * @param value The bytes for gender to set.
     * @return This builder for chaining.
     */
    public Builder setGenderBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      gender_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO)
  }

  // @@protoc_insertion_point(class_scope:ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO)
  private static final ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO();
  }

  public static ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OnlineUserInfoDialogVO>
      PARSER = new com.google.protobuf.AbstractParser<OnlineUserInfoDialogVO>() {
    @java.lang.Override
    public OnlineUserInfoDialogVO parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OnlineUserInfoDialogVO(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OnlineUserInfoDialogVO> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OnlineUserInfoDialogVO> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ly.pp.justpiano3.protobuf.vo.OnlineUserInfoDialogVO getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

