// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OnlineResponseProtocol.proto

package protobuf.vo;

public interface OnlineLoadRoomUserListVOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.vo.OnlineLoadRoomUserListVO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 用户列表
   * </pre>
   *
   * <code>repeated .protobuf.vo.OnlineLoadRoomUserVO load_room_user = 1;</code>
   */
  java.util.List<protobuf.vo.OnlineLoadRoomUserVO> 
      getLoadRoomUserList();
  /**
   * <pre>
   * 用户列表
   * </pre>
   *
   * <code>repeated .protobuf.vo.OnlineLoadRoomUserVO load_room_user = 1;</code>
   */
  protobuf.vo.OnlineLoadRoomUserVO getLoadRoomUser(int index);
  /**
   * <pre>
   * 用户列表
   * </pre>
   *
   * <code>repeated .protobuf.vo.OnlineLoadRoomUserVO load_room_user = 1;</code>
   */
  int getLoadRoomUserCount();
  /**
   * <pre>
   * 用户列表
   * </pre>
   *
   * <code>repeated .protobuf.vo.OnlineLoadRoomUserVO load_room_user = 1;</code>
   */
  java.util.List<? extends protobuf.vo.OnlineLoadRoomUserVOOrBuilder> 
      getLoadRoomUserOrBuilderList();
  /**
   * <pre>
   * 用户列表
   * </pre>
   *
   * <code>repeated .protobuf.vo.OnlineLoadRoomUserVO load_room_user = 1;</code>
   */
  protobuf.vo.OnlineLoadRoomUserVOOrBuilder getLoadRoomUserOrBuilder(
      int index);

  /**
   * <pre>
   * 房间id
   * </pre>
   *
   * <code>uint32 room_id = 2;</code>
   * @return The roomId.
   */
  int getRoomId();

  /**
   * <pre>
   * 房间是否弹奏中
   * </pre>
   *
   * <code>bool is_playing = 3;</code>
   * @return The isPlaying.
   */
  boolean getIsPlaying();

  /**
   * <pre>
   * 房间是否加密
   * </pre>
   *
   * <code>bool is_encrypt = 4;</code>
   * @return The isEncrypt.
   */
  boolean getIsEncrypt();
}
