// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OnlineResponseProtocol.proto

package protobuf.vo;

/**
 * <pre>
 * 主界面查看搭档
 * </pre>
 *
 * Protobuf type {@code protobuf.vo.OnlineLoadUserCoupleVO}
 */
public final class OnlineLoadUserCoupleVO extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protobuf.vo.OnlineLoadUserCoupleVO)
    OnlineLoadUserCoupleVOOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OnlineLoadUserCoupleVO.newBuilder() to construct.
  private OnlineLoadUserCoupleVO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OnlineLoadUserCoupleVO() {
    name_ = "";
    declaration_ = "";
    gender_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OnlineLoadUserCoupleVO();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OnlineLoadUserCoupleVO(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            protobuf.vo.OnlineClothesVO.Builder subBuilder = null;
            if (clothes_ != null) {
              subBuilder = clothes_.toBuilder();
            }
            clothes_ = input.readMessage(protobuf.vo.OnlineClothesVO.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(clothes_);
              clothes_ = subBuilder.buildPartial();
            }

            break;
          }
          case 24: {

            blessing_ = input.readUInt32();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            declaration_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            gender_ = s;
            break;
          }
          case 48: {

            cl_ = input.readUInt32();
            break;
          }
          case 56: {

            lv_ = input.readUInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protobuf.vo.OnlineResponse.internal_static_protobuf_vo_OnlineLoadUserCoupleVO_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protobuf.vo.OnlineResponse.internal_static_protobuf_vo_OnlineLoadUserCoupleVO_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protobuf.vo.OnlineLoadUserCoupleVO.class, protobuf.vo.OnlineLoadUserCoupleVO.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   * 搭档名称
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 搭档名称
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLOTHES_FIELD_NUMBER = 2;
  private protobuf.vo.OnlineClothesVO clothes_;
  /**
   * <pre>
   * 搭档服装
   * </pre>
   *
   * <code>.protobuf.vo.OnlineClothesVO clothes = 2;</code>
   * @return Whether the clothes field is set.
   */
  @java.lang.Override
  public boolean hasClothes() {
    return clothes_ != null;
  }
  /**
   * <pre>
   * 搭档服装
   * </pre>
   *
   * <code>.protobuf.vo.OnlineClothesVO clothes = 2;</code>
   * @return The clothes.
   */
  @java.lang.Override
  public protobuf.vo.OnlineClothesVO getClothes() {
    return clothes_ == null ? protobuf.vo.OnlineClothesVO.getDefaultInstance() : clothes_;
  }
  /**
   * <pre>
   * 搭档服装
   * </pre>
   *
   * <code>.protobuf.vo.OnlineClothesVO clothes = 2;</code>
   */
  @java.lang.Override
  public protobuf.vo.OnlineClothesVOOrBuilder getClothesOrBuilder() {
    return getClothes();
  }

  public static final int BLESSING_FIELD_NUMBER = 3;
  private int blessing_;
  /**
   * <pre>
   * 搭档祝福数
   * </pre>
   *
   * <code>uint32 blessing = 3;</code>
   * @return The blessing.
   */
  @java.lang.Override
  public int getBlessing() {
    return blessing_;
  }

  public static final int DECLARATION_FIELD_NUMBER = 4;
  private volatile java.lang.Object declaration_;
  /**
   * <pre>
   * 搭档祝语
   * </pre>
   *
   * <code>string declaration = 4;</code>
   * @return The declaration.
   */
  @java.lang.Override
  public java.lang.String getDeclaration() {
    java.lang.Object ref = declaration_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      declaration_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 搭档祝语
   * </pre>
   *
   * <code>string declaration = 4;</code>
   * @return The bytes for declaration.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeclarationBytes() {
    java.lang.Object ref = declaration_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      declaration_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GENDER_FIELD_NUMBER = 5;
  private volatile java.lang.Object gender_;
  /**
   * <pre>
   * 搭档性别
   * </pre>
   *
   * <code>string gender = 5;</code>
   * @return The gender.
   */
  @java.lang.Override
  public java.lang.String getGender() {
    java.lang.Object ref = gender_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      gender_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 搭档性别
   * </pre>
   *
   * <code>string gender = 5;</code>
   * @return The bytes for gender.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGenderBytes() {
    java.lang.Object ref = gender_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gender_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CL_FIELD_NUMBER = 6;
  private int cl_;
  /**
   * <pre>
   * 搭档考级
   * </pre>
   *
   * <code>uint32 cl = 6;</code>
   * @return The cl.
   */
  @java.lang.Override
  public int getCl() {
    return cl_;
  }

  public static final int LV_FIELD_NUMBER = 7;
  private int lv_;
  /**
   * <pre>
   * 搭档等级
   * </pre>
   *
   * <code>uint32 lv = 7;</code>
   * @return The lv.
   */
  @java.lang.Override
  public int getLv() {
    return lv_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (clothes_ != null) {
      output.writeMessage(2, getClothes());
    }
    if (blessing_ != 0) {
      output.writeUInt32(3, blessing_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(declaration_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, declaration_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(gender_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, gender_);
    }
    if (cl_ != 0) {
      output.writeUInt32(6, cl_);
    }
    if (lv_ != 0) {
      output.writeUInt32(7, lv_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (clothes_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getClothes());
    }
    if (blessing_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, blessing_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(declaration_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, declaration_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(gender_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, gender_);
    }
    if (cl_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(6, cl_);
    }
    if (lv_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(7, lv_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protobuf.vo.OnlineLoadUserCoupleVO)) {
      return super.equals(obj);
    }
    protobuf.vo.OnlineLoadUserCoupleVO other = (protobuf.vo.OnlineLoadUserCoupleVO) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (hasClothes() != other.hasClothes()) return false;
    if (hasClothes()) {
      if (!getClothes()
          .equals(other.getClothes())) return false;
    }
    if (getBlessing()
        != other.getBlessing()) return false;
    if (!getDeclaration()
        .equals(other.getDeclaration())) return false;
    if (!getGender()
        .equals(other.getGender())) return false;
    if (getCl()
        != other.getCl()) return false;
    if (getLv()
        != other.getLv()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (hasClothes()) {
      hash = (37 * hash) + CLOTHES_FIELD_NUMBER;
      hash = (53 * hash) + getClothes().hashCode();
    }
    hash = (37 * hash) + BLESSING_FIELD_NUMBER;
    hash = (53 * hash) + getBlessing();
    hash = (37 * hash) + DECLARATION_FIELD_NUMBER;
    hash = (53 * hash) + getDeclaration().hashCode();
    hash = (37 * hash) + GENDER_FIELD_NUMBER;
    hash = (53 * hash) + getGender().hashCode();
    hash = (37 * hash) + CL_FIELD_NUMBER;
    hash = (53 * hash) + getCl();
    hash = (37 * hash) + LV_FIELD_NUMBER;
    hash = (53 * hash) + getLv();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protobuf.vo.OnlineLoadUserCoupleVO parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.vo.OnlineLoadUserCoupleVO parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.vo.OnlineLoadUserCoupleVO parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.vo.OnlineLoadUserCoupleVO parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.vo.OnlineLoadUserCoupleVO parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.vo.OnlineLoadUserCoupleVO parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.vo.OnlineLoadUserCoupleVO parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuf.vo.OnlineLoadUserCoupleVO parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuf.vo.OnlineLoadUserCoupleVO parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protobuf.vo.OnlineLoadUserCoupleVO parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuf.vo.OnlineLoadUserCoupleVO parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuf.vo.OnlineLoadUserCoupleVO parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protobuf.vo.OnlineLoadUserCoupleVO prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 主界面查看搭档
   * </pre>
   *
   * Protobuf type {@code protobuf.vo.OnlineLoadUserCoupleVO}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protobuf.vo.OnlineLoadUserCoupleVO)
      protobuf.vo.OnlineLoadUserCoupleVOOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.vo.OnlineResponse.internal_static_protobuf_vo_OnlineLoadUserCoupleVO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.vo.OnlineResponse.internal_static_protobuf_vo_OnlineLoadUserCoupleVO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.vo.OnlineLoadUserCoupleVO.class, protobuf.vo.OnlineLoadUserCoupleVO.Builder.class);
    }

    // Construct using protobuf.vo.OnlineLoadUserCoupleVO.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      if (clothesBuilder_ == null) {
        clothes_ = null;
      } else {
        clothes_ = null;
        clothesBuilder_ = null;
      }
      blessing_ = 0;

      declaration_ = "";

      gender_ = "";

      cl_ = 0;

      lv_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protobuf.vo.OnlineResponse.internal_static_protobuf_vo_OnlineLoadUserCoupleVO_descriptor;
    }

    @java.lang.Override
    public protobuf.vo.OnlineLoadUserCoupleVO getDefaultInstanceForType() {
      return protobuf.vo.OnlineLoadUserCoupleVO.getDefaultInstance();
    }

    @java.lang.Override
    public protobuf.vo.OnlineLoadUserCoupleVO build() {
      protobuf.vo.OnlineLoadUserCoupleVO result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protobuf.vo.OnlineLoadUserCoupleVO buildPartial() {
      protobuf.vo.OnlineLoadUserCoupleVO result = new protobuf.vo.OnlineLoadUserCoupleVO(this);
      result.name_ = name_;
      if (clothesBuilder_ == null) {
        result.clothes_ = clothes_;
      } else {
        result.clothes_ = clothesBuilder_.build();
      }
      result.blessing_ = blessing_;
      result.declaration_ = declaration_;
      result.gender_ = gender_;
      result.cl_ = cl_;
      result.lv_ = lv_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protobuf.vo.OnlineLoadUserCoupleVO) {
        return mergeFrom((protobuf.vo.OnlineLoadUserCoupleVO)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protobuf.vo.OnlineLoadUserCoupleVO other) {
      if (other == protobuf.vo.OnlineLoadUserCoupleVO.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.hasClothes()) {
        mergeClothes(other.getClothes());
      }
      if (other.getBlessing() != 0) {
        setBlessing(other.getBlessing());
      }
      if (!other.getDeclaration().isEmpty()) {
        declaration_ = other.declaration_;
        onChanged();
      }
      if (!other.getGender().isEmpty()) {
        gender_ = other.gender_;
        onChanged();
      }
      if (other.getCl() != 0) {
        setCl(other.getCl());
      }
      if (other.getLv() != 0) {
        setLv(other.getLv());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protobuf.vo.OnlineLoadUserCoupleVO parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protobuf.vo.OnlineLoadUserCoupleVO) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * 搭档名称
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 搭档名称
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 搭档名称
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 搭档名称
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 搭档名称
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private protobuf.vo.OnlineClothesVO clothes_;
    private com.google.protobuf.SingleFieldBuilderV3<
        protobuf.vo.OnlineClothesVO, protobuf.vo.OnlineClothesVO.Builder, protobuf.vo.OnlineClothesVOOrBuilder> clothesBuilder_;
    /**
     * <pre>
     * 搭档服装
     * </pre>
     *
     * <code>.protobuf.vo.OnlineClothesVO clothes = 2;</code>
     * @return Whether the clothes field is set.
     */
    public boolean hasClothes() {
      return clothesBuilder_ != null || clothes_ != null;
    }
    /**
     * <pre>
     * 搭档服装
     * </pre>
     *
     * <code>.protobuf.vo.OnlineClothesVO clothes = 2;</code>
     * @return The clothes.
     */
    public protobuf.vo.OnlineClothesVO getClothes() {
      if (clothesBuilder_ == null) {
        return clothes_ == null ? protobuf.vo.OnlineClothesVO.getDefaultInstance() : clothes_;
      } else {
        return clothesBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 搭档服装
     * </pre>
     *
     * <code>.protobuf.vo.OnlineClothesVO clothes = 2;</code>
     */
    public Builder setClothes(protobuf.vo.OnlineClothesVO value) {
      if (clothesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        clothes_ = value;
        onChanged();
      } else {
        clothesBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 搭档服装
     * </pre>
     *
     * <code>.protobuf.vo.OnlineClothesVO clothes = 2;</code>
     */
    public Builder setClothes(
        protobuf.vo.OnlineClothesVO.Builder builderForValue) {
      if (clothesBuilder_ == null) {
        clothes_ = builderForValue.build();
        onChanged();
      } else {
        clothesBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 搭档服装
     * </pre>
     *
     * <code>.protobuf.vo.OnlineClothesVO clothes = 2;</code>
     */
    public Builder mergeClothes(protobuf.vo.OnlineClothesVO value) {
      if (clothesBuilder_ == null) {
        if (clothes_ != null) {
          clothes_ =
            protobuf.vo.OnlineClothesVO.newBuilder(clothes_).mergeFrom(value).buildPartial();
        } else {
          clothes_ = value;
        }
        onChanged();
      } else {
        clothesBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 搭档服装
     * </pre>
     *
     * <code>.protobuf.vo.OnlineClothesVO clothes = 2;</code>
     */
    public Builder clearClothes() {
      if (clothesBuilder_ == null) {
        clothes_ = null;
        onChanged();
      } else {
        clothes_ = null;
        clothesBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 搭档服装
     * </pre>
     *
     * <code>.protobuf.vo.OnlineClothesVO clothes = 2;</code>
     */
    public protobuf.vo.OnlineClothesVO.Builder getClothesBuilder() {
      
      onChanged();
      return getClothesFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 搭档服装
     * </pre>
     *
     * <code>.protobuf.vo.OnlineClothesVO clothes = 2;</code>
     */
    public protobuf.vo.OnlineClothesVOOrBuilder getClothesOrBuilder() {
      if (clothesBuilder_ != null) {
        return clothesBuilder_.getMessageOrBuilder();
      } else {
        return clothes_ == null ?
            protobuf.vo.OnlineClothesVO.getDefaultInstance() : clothes_;
      }
    }
    /**
     * <pre>
     * 搭档服装
     * </pre>
     *
     * <code>.protobuf.vo.OnlineClothesVO clothes = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        protobuf.vo.OnlineClothesVO, protobuf.vo.OnlineClothesVO.Builder, protobuf.vo.OnlineClothesVOOrBuilder> 
        getClothesFieldBuilder() {
      if (clothesBuilder_ == null) {
        clothesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            protobuf.vo.OnlineClothesVO, protobuf.vo.OnlineClothesVO.Builder, protobuf.vo.OnlineClothesVOOrBuilder>(
                getClothes(),
                getParentForChildren(),
                isClean());
        clothes_ = null;
      }
      return clothesBuilder_;
    }

    private int blessing_ ;
    /**
     * <pre>
     * 搭档祝福数
     * </pre>
     *
     * <code>uint32 blessing = 3;</code>
     * @return The blessing.
     */
    @java.lang.Override
    public int getBlessing() {
      return blessing_;
    }
    /**
     * <pre>
     * 搭档祝福数
     * </pre>
     *
     * <code>uint32 blessing = 3;</code>
     * @param value The blessing to set.
     * @return This builder for chaining.
     */
    public Builder setBlessing(int value) {
      
      blessing_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 搭档祝福数
     * </pre>
     *
     * <code>uint32 blessing = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBlessing() {
      
      blessing_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object declaration_ = "";
    /**
     * <pre>
     * 搭档祝语
     * </pre>
     *
     * <code>string declaration = 4;</code>
     * @return The declaration.
     */
    public java.lang.String getDeclaration() {
      java.lang.Object ref = declaration_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        declaration_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 搭档祝语
     * </pre>
     *
     * <code>string declaration = 4;</code>
     * @return The bytes for declaration.
     */
    public com.google.protobuf.ByteString
        getDeclarationBytes() {
      java.lang.Object ref = declaration_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        declaration_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 搭档祝语
     * </pre>
     *
     * <code>string declaration = 4;</code>
     * @param value The declaration to set.
     * @return This builder for chaining.
     */
    public Builder setDeclaration(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      declaration_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 搭档祝语
     * </pre>
     *
     * <code>string declaration = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeclaration() {
      
      declaration_ = getDefaultInstance().getDeclaration();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 搭档祝语
     * </pre>
     *
     * <code>string declaration = 4;</code>
     * @param value The bytes for declaration to set.
     * @return This builder for chaining.
     */
    public Builder setDeclarationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      declaration_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object gender_ = "";
    /**
     * <pre>
     * 搭档性别
     * </pre>
     *
     * <code>string gender = 5;</code>
     * @return The gender.
     */
    public java.lang.String getGender() {
      java.lang.Object ref = gender_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gender_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 搭档性别
     * </pre>
     *
     * <code>string gender = 5;</code>
     * @return The bytes for gender.
     */
    public com.google.protobuf.ByteString
        getGenderBytes() {
      java.lang.Object ref = gender_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 搭档性别
     * </pre>
     *
     * <code>string gender = 5;</code>
     * @param value The gender to set.
     * @return This builder for chaining.
     */
    public Builder setGender(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      gender_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 搭档性别
     * </pre>
     *
     * <code>string gender = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearGender() {
      
      gender_ = getDefaultInstance().getGender();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 搭档性别
     * </pre>
     *
     * <code>string gender = 5;</code>
     * @param value The bytes for gender to set.
     * @return This builder for chaining.
     */
    public Builder setGenderBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      gender_ = value;
      onChanged();
      return this;
    }

    private int cl_ ;
    /**
     * <pre>
     * 搭档考级
     * </pre>
     *
     * <code>uint32 cl = 6;</code>
     * @return The cl.
     */
    @java.lang.Override
    public int getCl() {
      return cl_;
    }
    /**
     * <pre>
     * 搭档考级
     * </pre>
     *
     * <code>uint32 cl = 6;</code>
     * @param value The cl to set.
     * @return This builder for chaining.
     */
    public Builder setCl(int value) {
      
      cl_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 搭档考级
     * </pre>
     *
     * <code>uint32 cl = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearCl() {
      
      cl_ = 0;
      onChanged();
      return this;
    }

    private int lv_ ;
    /**
     * <pre>
     * 搭档等级
     * </pre>
     *
     * <code>uint32 lv = 7;</code>
     * @return The lv.
     */
    @java.lang.Override
    public int getLv() {
      return lv_;
    }
    /**
     * <pre>
     * 搭档等级
     * </pre>
     *
     * <code>uint32 lv = 7;</code>
     * @param value The lv to set.
     * @return This builder for chaining.
     */
    public Builder setLv(int value) {
      
      lv_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 搭档等级
     * </pre>
     *
     * <code>uint32 lv = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearLv() {
      
      lv_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protobuf.vo.OnlineLoadUserCoupleVO)
  }

  // @@protoc_insertion_point(class_scope:protobuf.vo.OnlineLoadUserCoupleVO)
  private static final protobuf.vo.OnlineLoadUserCoupleVO DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protobuf.vo.OnlineLoadUserCoupleVO();
  }

  public static protobuf.vo.OnlineLoadUserCoupleVO getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OnlineLoadUserCoupleVO>
      PARSER = new com.google.protobuf.AbstractParser<OnlineLoadUserCoupleVO>() {
    @java.lang.Override
    public OnlineLoadUserCoupleVO parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OnlineLoadUserCoupleVO(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OnlineLoadUserCoupleVO> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OnlineLoadUserCoupleVO> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protobuf.vo.OnlineLoadUserCoupleVO getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

