// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OnlineResponseProtocol.proto

package protobuf.vo;

/**
 * <pre>
 * 查看好友、私信和主界面查看搭档
 * </pre>
 *
 * Protobuf type {@code protobuf.vo.OnlineLoadUserInfoVO}
 */
public final class OnlineLoadUserInfoVO extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protobuf.vo.OnlineLoadUserInfoVO)
    OnlineLoadUserInfoVOOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OnlineLoadUserInfoVO.newBuilder() to construct.
  private OnlineLoadUserInfoVO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OnlineLoadUserInfoVO() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OnlineLoadUserInfoVO();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OnlineLoadUserInfoVO(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            type_ = input.readUInt32();
            break;
          }
          case 18: {
            protobuf.vo.OnlineLoadUserFriendVO.Builder subBuilder = null;
            if (userInfoCase_ == 2) {
              subBuilder = ((protobuf.vo.OnlineLoadUserFriendVO) userInfo_).toBuilder();
            }
            userInfo_ =
                input.readMessage(protobuf.vo.OnlineLoadUserFriendVO.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((protobuf.vo.OnlineLoadUserFriendVO) userInfo_);
              userInfo_ = subBuilder.buildPartial();
            }
            userInfoCase_ = 2;
            break;
          }
          case 26: {
            protobuf.vo.OnlineLoadUserMailVO.Builder subBuilder = null;
            if (userInfoCase_ == 3) {
              subBuilder = ((protobuf.vo.OnlineLoadUserMailVO) userInfo_).toBuilder();
            }
            userInfo_ =
                input.readMessage(protobuf.vo.OnlineLoadUserMailVO.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((protobuf.vo.OnlineLoadUserMailVO) userInfo_);
              userInfo_ = subBuilder.buildPartial();
            }
            userInfoCase_ = 3;
            break;
          }
          case 34: {
            protobuf.vo.OnlineLoadUserCoupleVO.Builder subBuilder = null;
            if (userInfoCase_ == 4) {
              subBuilder = ((protobuf.vo.OnlineLoadUserCoupleVO) userInfo_).toBuilder();
            }
            userInfo_ =
                input.readMessage(protobuf.vo.OnlineLoadUserCoupleVO.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((protobuf.vo.OnlineLoadUserCoupleVO) userInfo_);
              userInfo_ = subBuilder.buildPartial();
            }
            userInfoCase_ = 4;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protobuf.vo.OnlineResponse.internal_static_protobuf_vo_OnlineLoadUserInfoVO_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protobuf.vo.OnlineResponse.internal_static_protobuf_vo_OnlineLoadUserInfoVO_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protobuf.vo.OnlineLoadUserInfoVO.class, protobuf.vo.OnlineLoadUserInfoVO.Builder.class);
  }

  private int userInfoCase_ = 0;
  private java.lang.Object userInfo_;
  public enum UserInfoCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    LOAD_USER_FRIEND(2),
    LOAD_USER_MAIL(3),
    LOAD_USER_COUPLE(4),
    USERINFO_NOT_SET(0);
    private final int value;
    private UserInfoCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static UserInfoCase valueOf(int value) {
      return forNumber(value);
    }

    public static UserInfoCase forNumber(int value) {
      switch (value) {
        case 2: return LOAD_USER_FRIEND;
        case 3: return LOAD_USER_MAIL;
        case 4: return LOAD_USER_COUPLE;
        case 0: return USERINFO_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public UserInfoCase
  getUserInfoCase() {
    return UserInfoCase.forNumber(
        userInfoCase_);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <pre>
   * 消息类型
   * </pre>
   *
   * <code>uint32 type = 1;</code>
   * @return The type.
   */
  @java.lang.Override
  public int getType() {
    return type_;
  }

  public static final int LOAD_USER_FRIEND_FIELD_NUMBER = 2;
  /**
   * <pre>
   * 查看好友
   * </pre>
   *
   * <code>.protobuf.vo.OnlineLoadUserFriendVO load_user_friend = 2;</code>
   * @return Whether the loadUserFriend field is set.
   */
  @java.lang.Override
  public boolean hasLoadUserFriend() {
    return userInfoCase_ == 2;
  }
  /**
   * <pre>
   * 查看好友
   * </pre>
   *
   * <code>.protobuf.vo.OnlineLoadUserFriendVO load_user_friend = 2;</code>
   * @return The loadUserFriend.
   */
  @java.lang.Override
  public protobuf.vo.OnlineLoadUserFriendVO getLoadUserFriend() {
    if (userInfoCase_ == 2) {
       return (protobuf.vo.OnlineLoadUserFriendVO) userInfo_;
    }
    return protobuf.vo.OnlineLoadUserFriendVO.getDefaultInstance();
  }
  /**
   * <pre>
   * 查看好友
   * </pre>
   *
   * <code>.protobuf.vo.OnlineLoadUserFriendVO load_user_friend = 2;</code>
   */
  @java.lang.Override
  public protobuf.vo.OnlineLoadUserFriendVOOrBuilder getLoadUserFriendOrBuilder() {
    if (userInfoCase_ == 2) {
       return (protobuf.vo.OnlineLoadUserFriendVO) userInfo_;
    }
    return protobuf.vo.OnlineLoadUserFriendVO.getDefaultInstance();
  }

  public static final int LOAD_USER_MAIL_FIELD_NUMBER = 3;
  /**
   * <pre>
   * 查看私信
   * </pre>
   *
   * <code>.protobuf.vo.OnlineLoadUserMailVO load_user_mail = 3;</code>
   * @return Whether the loadUserMail field is set.
   */
  @java.lang.Override
  public boolean hasLoadUserMail() {
    return userInfoCase_ == 3;
  }
  /**
   * <pre>
   * 查看私信
   * </pre>
   *
   * <code>.protobuf.vo.OnlineLoadUserMailVO load_user_mail = 3;</code>
   * @return The loadUserMail.
   */
  @java.lang.Override
  public protobuf.vo.OnlineLoadUserMailVO getLoadUserMail() {
    if (userInfoCase_ == 3) {
       return (protobuf.vo.OnlineLoadUserMailVO) userInfo_;
    }
    return protobuf.vo.OnlineLoadUserMailVO.getDefaultInstance();
  }
  /**
   * <pre>
   * 查看私信
   * </pre>
   *
   * <code>.protobuf.vo.OnlineLoadUserMailVO load_user_mail = 3;</code>
   */
  @java.lang.Override
  public protobuf.vo.OnlineLoadUserMailVOOrBuilder getLoadUserMailOrBuilder() {
    if (userInfoCase_ == 3) {
       return (protobuf.vo.OnlineLoadUserMailVO) userInfo_;
    }
    return protobuf.vo.OnlineLoadUserMailVO.getDefaultInstance();
  }

  public static final int LOAD_USER_COUPLE_FIELD_NUMBER = 4;
  /**
   * <pre>
   * 主界面查看搭档
   * </pre>
   *
   * <code>.protobuf.vo.OnlineLoadUserCoupleVO load_user_couple = 4;</code>
   * @return Whether the loadUserCouple field is set.
   */
  @java.lang.Override
  public boolean hasLoadUserCouple() {
    return userInfoCase_ == 4;
  }
  /**
   * <pre>
   * 主界面查看搭档
   * </pre>
   *
   * <code>.protobuf.vo.OnlineLoadUserCoupleVO load_user_couple = 4;</code>
   * @return The loadUserCouple.
   */
  @java.lang.Override
  public protobuf.vo.OnlineLoadUserCoupleVO getLoadUserCouple() {
    if (userInfoCase_ == 4) {
       return (protobuf.vo.OnlineLoadUserCoupleVO) userInfo_;
    }
    return protobuf.vo.OnlineLoadUserCoupleVO.getDefaultInstance();
  }
  /**
   * <pre>
   * 主界面查看搭档
   * </pre>
   *
   * <code>.protobuf.vo.OnlineLoadUserCoupleVO load_user_couple = 4;</code>
   */
  @java.lang.Override
  public protobuf.vo.OnlineLoadUserCoupleVOOrBuilder getLoadUserCoupleOrBuilder() {
    if (userInfoCase_ == 4) {
       return (protobuf.vo.OnlineLoadUserCoupleVO) userInfo_;
    }
    return protobuf.vo.OnlineLoadUserCoupleVO.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != 0) {
      output.writeUInt32(1, type_);
    }
    if (userInfoCase_ == 2) {
      output.writeMessage(2, (protobuf.vo.OnlineLoadUserFriendVO) userInfo_);
    }
    if (userInfoCase_ == 3) {
      output.writeMessage(3, (protobuf.vo.OnlineLoadUserMailVO) userInfo_);
    }
    if (userInfoCase_ == 4) {
      output.writeMessage(4, (protobuf.vo.OnlineLoadUserCoupleVO) userInfo_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, type_);
    }
    if (userInfoCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (protobuf.vo.OnlineLoadUserFriendVO) userInfo_);
    }
    if (userInfoCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (protobuf.vo.OnlineLoadUserMailVO) userInfo_);
    }
    if (userInfoCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (protobuf.vo.OnlineLoadUserCoupleVO) userInfo_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protobuf.vo.OnlineLoadUserInfoVO)) {
      return super.equals(obj);
    }
    protobuf.vo.OnlineLoadUserInfoVO other = (protobuf.vo.OnlineLoadUserInfoVO) obj;

    if (getType()
        != other.getType()) return false;
    if (!getUserInfoCase().equals(other.getUserInfoCase())) return false;
    switch (userInfoCase_) {
      case 2:
        if (!getLoadUserFriend()
            .equals(other.getLoadUserFriend())) return false;
        break;
      case 3:
        if (!getLoadUserMail()
            .equals(other.getLoadUserMail())) return false;
        break;
      case 4:
        if (!getLoadUserCouple()
            .equals(other.getLoadUserCouple())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType();
    switch (userInfoCase_) {
      case 2:
        hash = (37 * hash) + LOAD_USER_FRIEND_FIELD_NUMBER;
        hash = (53 * hash) + getLoadUserFriend().hashCode();
        break;
      case 3:
        hash = (37 * hash) + LOAD_USER_MAIL_FIELD_NUMBER;
        hash = (53 * hash) + getLoadUserMail().hashCode();
        break;
      case 4:
        hash = (37 * hash) + LOAD_USER_COUPLE_FIELD_NUMBER;
        hash = (53 * hash) + getLoadUserCouple().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protobuf.vo.OnlineLoadUserInfoVO parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.vo.OnlineLoadUserInfoVO parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.vo.OnlineLoadUserInfoVO parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.vo.OnlineLoadUserInfoVO parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.vo.OnlineLoadUserInfoVO parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protobuf.vo.OnlineLoadUserInfoVO parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protobuf.vo.OnlineLoadUserInfoVO parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuf.vo.OnlineLoadUserInfoVO parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuf.vo.OnlineLoadUserInfoVO parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protobuf.vo.OnlineLoadUserInfoVO parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protobuf.vo.OnlineLoadUserInfoVO parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protobuf.vo.OnlineLoadUserInfoVO parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protobuf.vo.OnlineLoadUserInfoVO prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 查看好友、私信和主界面查看搭档
   * </pre>
   *
   * Protobuf type {@code protobuf.vo.OnlineLoadUserInfoVO}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protobuf.vo.OnlineLoadUserInfoVO)
      protobuf.vo.OnlineLoadUserInfoVOOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.vo.OnlineResponse.internal_static_protobuf_vo_OnlineLoadUserInfoVO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.vo.OnlineResponse.internal_static_protobuf_vo_OnlineLoadUserInfoVO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.vo.OnlineLoadUserInfoVO.class, protobuf.vo.OnlineLoadUserInfoVO.Builder.class);
    }

    // Construct using protobuf.vo.OnlineLoadUserInfoVO.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      type_ = 0;

      userInfoCase_ = 0;
      userInfo_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protobuf.vo.OnlineResponse.internal_static_protobuf_vo_OnlineLoadUserInfoVO_descriptor;
    }

    @java.lang.Override
    public protobuf.vo.OnlineLoadUserInfoVO getDefaultInstanceForType() {
      return protobuf.vo.OnlineLoadUserInfoVO.getDefaultInstance();
    }

    @java.lang.Override
    public protobuf.vo.OnlineLoadUserInfoVO build() {
      protobuf.vo.OnlineLoadUserInfoVO result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protobuf.vo.OnlineLoadUserInfoVO buildPartial() {
      protobuf.vo.OnlineLoadUserInfoVO result = new protobuf.vo.OnlineLoadUserInfoVO(this);
      result.type_ = type_;
      if (userInfoCase_ == 2) {
        if (loadUserFriendBuilder_ == null) {
          result.userInfo_ = userInfo_;
        } else {
          result.userInfo_ = loadUserFriendBuilder_.build();
        }
      }
      if (userInfoCase_ == 3) {
        if (loadUserMailBuilder_ == null) {
          result.userInfo_ = userInfo_;
        } else {
          result.userInfo_ = loadUserMailBuilder_.build();
        }
      }
      if (userInfoCase_ == 4) {
        if (loadUserCoupleBuilder_ == null) {
          result.userInfo_ = userInfo_;
        } else {
          result.userInfo_ = loadUserCoupleBuilder_.build();
        }
      }
      result.userInfoCase_ = userInfoCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protobuf.vo.OnlineLoadUserInfoVO) {
        return mergeFrom((protobuf.vo.OnlineLoadUserInfoVO)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protobuf.vo.OnlineLoadUserInfoVO other) {
      if (other == protobuf.vo.OnlineLoadUserInfoVO.getDefaultInstance()) return this;
      if (other.getType() != 0) {
        setType(other.getType());
      }
      switch (other.getUserInfoCase()) {
        case LOAD_USER_FRIEND: {
          mergeLoadUserFriend(other.getLoadUserFriend());
          break;
        }
        case LOAD_USER_MAIL: {
          mergeLoadUserMail(other.getLoadUserMail());
          break;
        }
        case LOAD_USER_COUPLE: {
          mergeLoadUserCouple(other.getLoadUserCouple());
          break;
        }
        case USERINFO_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      protobuf.vo.OnlineLoadUserInfoVO parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (protobuf.vo.OnlineLoadUserInfoVO) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int userInfoCase_ = 0;
    private java.lang.Object userInfo_;
    public UserInfoCase
        getUserInfoCase() {
      return UserInfoCase.forNumber(
          userInfoCase_);
    }

    public Builder clearUserInfo() {
      userInfoCase_ = 0;
      userInfo_ = null;
      onChanged();
      return this;
    }


    private int type_ ;
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>uint32 type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>uint32 type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(int value) {
      
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>uint32 type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        protobuf.vo.OnlineLoadUserFriendVO, protobuf.vo.OnlineLoadUserFriendVO.Builder, protobuf.vo.OnlineLoadUserFriendVOOrBuilder> loadUserFriendBuilder_;
    /**
     * <pre>
     * 查看好友
     * </pre>
     *
     * <code>.protobuf.vo.OnlineLoadUserFriendVO load_user_friend = 2;</code>
     * @return Whether the loadUserFriend field is set.
     */
    @java.lang.Override
    public boolean hasLoadUserFriend() {
      return userInfoCase_ == 2;
    }
    /**
     * <pre>
     * 查看好友
     * </pre>
     *
     * <code>.protobuf.vo.OnlineLoadUserFriendVO load_user_friend = 2;</code>
     * @return The loadUserFriend.
     */
    @java.lang.Override
    public protobuf.vo.OnlineLoadUserFriendVO getLoadUserFriend() {
      if (loadUserFriendBuilder_ == null) {
        if (userInfoCase_ == 2) {
          return (protobuf.vo.OnlineLoadUserFriendVO) userInfo_;
        }
        return protobuf.vo.OnlineLoadUserFriendVO.getDefaultInstance();
      } else {
        if (userInfoCase_ == 2) {
          return loadUserFriendBuilder_.getMessage();
        }
        return protobuf.vo.OnlineLoadUserFriendVO.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * 查看好友
     * </pre>
     *
     * <code>.protobuf.vo.OnlineLoadUserFriendVO load_user_friend = 2;</code>
     */
    public Builder setLoadUserFriend(protobuf.vo.OnlineLoadUserFriendVO value) {
      if (loadUserFriendBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        userInfo_ = value;
        onChanged();
      } else {
        loadUserFriendBuilder_.setMessage(value);
      }
      userInfoCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * 查看好友
     * </pre>
     *
     * <code>.protobuf.vo.OnlineLoadUserFriendVO load_user_friend = 2;</code>
     */
    public Builder setLoadUserFriend(
        protobuf.vo.OnlineLoadUserFriendVO.Builder builderForValue) {
      if (loadUserFriendBuilder_ == null) {
        userInfo_ = builderForValue.build();
        onChanged();
      } else {
        loadUserFriendBuilder_.setMessage(builderForValue.build());
      }
      userInfoCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * 查看好友
     * </pre>
     *
     * <code>.protobuf.vo.OnlineLoadUserFriendVO load_user_friend = 2;</code>
     */
    public Builder mergeLoadUserFriend(protobuf.vo.OnlineLoadUserFriendVO value) {
      if (loadUserFriendBuilder_ == null) {
        if (userInfoCase_ == 2 &&
            userInfo_ != protobuf.vo.OnlineLoadUserFriendVO.getDefaultInstance()) {
          userInfo_ = protobuf.vo.OnlineLoadUserFriendVO.newBuilder((protobuf.vo.OnlineLoadUserFriendVO) userInfo_)
              .mergeFrom(value).buildPartial();
        } else {
          userInfo_ = value;
        }
        onChanged();
      } else {
        if (userInfoCase_ == 2) {
          loadUserFriendBuilder_.mergeFrom(value);
        }
        loadUserFriendBuilder_.setMessage(value);
      }
      userInfoCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * 查看好友
     * </pre>
     *
     * <code>.protobuf.vo.OnlineLoadUserFriendVO load_user_friend = 2;</code>
     */
    public Builder clearLoadUserFriend() {
      if (loadUserFriendBuilder_ == null) {
        if (userInfoCase_ == 2) {
          userInfoCase_ = 0;
          userInfo_ = null;
          onChanged();
        }
      } else {
        if (userInfoCase_ == 2) {
          userInfoCase_ = 0;
          userInfo_ = null;
        }
        loadUserFriendBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 查看好友
     * </pre>
     *
     * <code>.protobuf.vo.OnlineLoadUserFriendVO load_user_friend = 2;</code>
     */
    public protobuf.vo.OnlineLoadUserFriendVO.Builder getLoadUserFriendBuilder() {
      return getLoadUserFriendFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 查看好友
     * </pre>
     *
     * <code>.protobuf.vo.OnlineLoadUserFriendVO load_user_friend = 2;</code>
     */
    @java.lang.Override
    public protobuf.vo.OnlineLoadUserFriendVOOrBuilder getLoadUserFriendOrBuilder() {
      if ((userInfoCase_ == 2) && (loadUserFriendBuilder_ != null)) {
        return loadUserFriendBuilder_.getMessageOrBuilder();
      } else {
        if (userInfoCase_ == 2) {
          return (protobuf.vo.OnlineLoadUserFriendVO) userInfo_;
        }
        return protobuf.vo.OnlineLoadUserFriendVO.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * 查看好友
     * </pre>
     *
     * <code>.protobuf.vo.OnlineLoadUserFriendVO load_user_friend = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        protobuf.vo.OnlineLoadUserFriendVO, protobuf.vo.OnlineLoadUserFriendVO.Builder, protobuf.vo.OnlineLoadUserFriendVOOrBuilder> 
        getLoadUserFriendFieldBuilder() {
      if (loadUserFriendBuilder_ == null) {
        if (!(userInfoCase_ == 2)) {
          userInfo_ = protobuf.vo.OnlineLoadUserFriendVO.getDefaultInstance();
        }
        loadUserFriendBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            protobuf.vo.OnlineLoadUserFriendVO, protobuf.vo.OnlineLoadUserFriendVO.Builder, protobuf.vo.OnlineLoadUserFriendVOOrBuilder>(
                (protobuf.vo.OnlineLoadUserFriendVO) userInfo_,
                getParentForChildren(),
                isClean());
        userInfo_ = null;
      }
      userInfoCase_ = 2;
      onChanged();;
      return loadUserFriendBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        protobuf.vo.OnlineLoadUserMailVO, protobuf.vo.OnlineLoadUserMailVO.Builder, protobuf.vo.OnlineLoadUserMailVOOrBuilder> loadUserMailBuilder_;
    /**
     * <pre>
     * 查看私信
     * </pre>
     *
     * <code>.protobuf.vo.OnlineLoadUserMailVO load_user_mail = 3;</code>
     * @return Whether the loadUserMail field is set.
     */
    @java.lang.Override
    public boolean hasLoadUserMail() {
      return userInfoCase_ == 3;
    }
    /**
     * <pre>
     * 查看私信
     * </pre>
     *
     * <code>.protobuf.vo.OnlineLoadUserMailVO load_user_mail = 3;</code>
     * @return The loadUserMail.
     */
    @java.lang.Override
    public protobuf.vo.OnlineLoadUserMailVO getLoadUserMail() {
      if (loadUserMailBuilder_ == null) {
        if (userInfoCase_ == 3) {
          return (protobuf.vo.OnlineLoadUserMailVO) userInfo_;
        }
        return protobuf.vo.OnlineLoadUserMailVO.getDefaultInstance();
      } else {
        if (userInfoCase_ == 3) {
          return loadUserMailBuilder_.getMessage();
        }
        return protobuf.vo.OnlineLoadUserMailVO.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * 查看私信
     * </pre>
     *
     * <code>.protobuf.vo.OnlineLoadUserMailVO load_user_mail = 3;</code>
     */
    public Builder setLoadUserMail(protobuf.vo.OnlineLoadUserMailVO value) {
      if (loadUserMailBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        userInfo_ = value;
        onChanged();
      } else {
        loadUserMailBuilder_.setMessage(value);
      }
      userInfoCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * 查看私信
     * </pre>
     *
     * <code>.protobuf.vo.OnlineLoadUserMailVO load_user_mail = 3;</code>
     */
    public Builder setLoadUserMail(
        protobuf.vo.OnlineLoadUserMailVO.Builder builderForValue) {
      if (loadUserMailBuilder_ == null) {
        userInfo_ = builderForValue.build();
        onChanged();
      } else {
        loadUserMailBuilder_.setMessage(builderForValue.build());
      }
      userInfoCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * 查看私信
     * </pre>
     *
     * <code>.protobuf.vo.OnlineLoadUserMailVO load_user_mail = 3;</code>
     */
    public Builder mergeLoadUserMail(protobuf.vo.OnlineLoadUserMailVO value) {
      if (loadUserMailBuilder_ == null) {
        if (userInfoCase_ == 3 &&
            userInfo_ != protobuf.vo.OnlineLoadUserMailVO.getDefaultInstance()) {
          userInfo_ = protobuf.vo.OnlineLoadUserMailVO.newBuilder((protobuf.vo.OnlineLoadUserMailVO) userInfo_)
              .mergeFrom(value).buildPartial();
        } else {
          userInfo_ = value;
        }
        onChanged();
      } else {
        if (userInfoCase_ == 3) {
          loadUserMailBuilder_.mergeFrom(value);
        }
        loadUserMailBuilder_.setMessage(value);
      }
      userInfoCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * 查看私信
     * </pre>
     *
     * <code>.protobuf.vo.OnlineLoadUserMailVO load_user_mail = 3;</code>
     */
    public Builder clearLoadUserMail() {
      if (loadUserMailBuilder_ == null) {
        if (userInfoCase_ == 3) {
          userInfoCase_ = 0;
          userInfo_ = null;
          onChanged();
        }
      } else {
        if (userInfoCase_ == 3) {
          userInfoCase_ = 0;
          userInfo_ = null;
        }
        loadUserMailBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 查看私信
     * </pre>
     *
     * <code>.protobuf.vo.OnlineLoadUserMailVO load_user_mail = 3;</code>
     */
    public protobuf.vo.OnlineLoadUserMailVO.Builder getLoadUserMailBuilder() {
      return getLoadUserMailFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 查看私信
     * </pre>
     *
     * <code>.protobuf.vo.OnlineLoadUserMailVO load_user_mail = 3;</code>
     */
    @java.lang.Override
    public protobuf.vo.OnlineLoadUserMailVOOrBuilder getLoadUserMailOrBuilder() {
      if ((userInfoCase_ == 3) && (loadUserMailBuilder_ != null)) {
        return loadUserMailBuilder_.getMessageOrBuilder();
      } else {
        if (userInfoCase_ == 3) {
          return (protobuf.vo.OnlineLoadUserMailVO) userInfo_;
        }
        return protobuf.vo.OnlineLoadUserMailVO.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * 查看私信
     * </pre>
     *
     * <code>.protobuf.vo.OnlineLoadUserMailVO load_user_mail = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        protobuf.vo.OnlineLoadUserMailVO, protobuf.vo.OnlineLoadUserMailVO.Builder, protobuf.vo.OnlineLoadUserMailVOOrBuilder> 
        getLoadUserMailFieldBuilder() {
      if (loadUserMailBuilder_ == null) {
        if (!(userInfoCase_ == 3)) {
          userInfo_ = protobuf.vo.OnlineLoadUserMailVO.getDefaultInstance();
        }
        loadUserMailBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            protobuf.vo.OnlineLoadUserMailVO, protobuf.vo.OnlineLoadUserMailVO.Builder, protobuf.vo.OnlineLoadUserMailVOOrBuilder>(
                (protobuf.vo.OnlineLoadUserMailVO) userInfo_,
                getParentForChildren(),
                isClean());
        userInfo_ = null;
      }
      userInfoCase_ = 3;
      onChanged();;
      return loadUserMailBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        protobuf.vo.OnlineLoadUserCoupleVO, protobuf.vo.OnlineLoadUserCoupleVO.Builder, protobuf.vo.OnlineLoadUserCoupleVOOrBuilder> loadUserCoupleBuilder_;
    /**
     * <pre>
     * 主界面查看搭档
     * </pre>
     *
     * <code>.protobuf.vo.OnlineLoadUserCoupleVO load_user_couple = 4;</code>
     * @return Whether the loadUserCouple field is set.
     */
    @java.lang.Override
    public boolean hasLoadUserCouple() {
      return userInfoCase_ == 4;
    }
    /**
     * <pre>
     * 主界面查看搭档
     * </pre>
     *
     * <code>.protobuf.vo.OnlineLoadUserCoupleVO load_user_couple = 4;</code>
     * @return The loadUserCouple.
     */
    @java.lang.Override
    public protobuf.vo.OnlineLoadUserCoupleVO getLoadUserCouple() {
      if (loadUserCoupleBuilder_ == null) {
        if (userInfoCase_ == 4) {
          return (protobuf.vo.OnlineLoadUserCoupleVO) userInfo_;
        }
        return protobuf.vo.OnlineLoadUserCoupleVO.getDefaultInstance();
      } else {
        if (userInfoCase_ == 4) {
          return loadUserCoupleBuilder_.getMessage();
        }
        return protobuf.vo.OnlineLoadUserCoupleVO.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * 主界面查看搭档
     * </pre>
     *
     * <code>.protobuf.vo.OnlineLoadUserCoupleVO load_user_couple = 4;</code>
     */
    public Builder setLoadUserCouple(protobuf.vo.OnlineLoadUserCoupleVO value) {
      if (loadUserCoupleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        userInfo_ = value;
        onChanged();
      } else {
        loadUserCoupleBuilder_.setMessage(value);
      }
      userInfoCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * 主界面查看搭档
     * </pre>
     *
     * <code>.protobuf.vo.OnlineLoadUserCoupleVO load_user_couple = 4;</code>
     */
    public Builder setLoadUserCouple(
        protobuf.vo.OnlineLoadUserCoupleVO.Builder builderForValue) {
      if (loadUserCoupleBuilder_ == null) {
        userInfo_ = builderForValue.build();
        onChanged();
      } else {
        loadUserCoupleBuilder_.setMessage(builderForValue.build());
      }
      userInfoCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * 主界面查看搭档
     * </pre>
     *
     * <code>.protobuf.vo.OnlineLoadUserCoupleVO load_user_couple = 4;</code>
     */
    public Builder mergeLoadUserCouple(protobuf.vo.OnlineLoadUserCoupleVO value) {
      if (loadUserCoupleBuilder_ == null) {
        if (userInfoCase_ == 4 &&
            userInfo_ != protobuf.vo.OnlineLoadUserCoupleVO.getDefaultInstance()) {
          userInfo_ = protobuf.vo.OnlineLoadUserCoupleVO.newBuilder((protobuf.vo.OnlineLoadUserCoupleVO) userInfo_)
              .mergeFrom(value).buildPartial();
        } else {
          userInfo_ = value;
        }
        onChanged();
      } else {
        if (userInfoCase_ == 4) {
          loadUserCoupleBuilder_.mergeFrom(value);
        }
        loadUserCoupleBuilder_.setMessage(value);
      }
      userInfoCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * 主界面查看搭档
     * </pre>
     *
     * <code>.protobuf.vo.OnlineLoadUserCoupleVO load_user_couple = 4;</code>
     */
    public Builder clearLoadUserCouple() {
      if (loadUserCoupleBuilder_ == null) {
        if (userInfoCase_ == 4) {
          userInfoCase_ = 0;
          userInfo_ = null;
          onChanged();
        }
      } else {
        if (userInfoCase_ == 4) {
          userInfoCase_ = 0;
          userInfo_ = null;
        }
        loadUserCoupleBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 主界面查看搭档
     * </pre>
     *
     * <code>.protobuf.vo.OnlineLoadUserCoupleVO load_user_couple = 4;</code>
     */
    public protobuf.vo.OnlineLoadUserCoupleVO.Builder getLoadUserCoupleBuilder() {
      return getLoadUserCoupleFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 主界面查看搭档
     * </pre>
     *
     * <code>.protobuf.vo.OnlineLoadUserCoupleVO load_user_couple = 4;</code>
     */
    @java.lang.Override
    public protobuf.vo.OnlineLoadUserCoupleVOOrBuilder getLoadUserCoupleOrBuilder() {
      if ((userInfoCase_ == 4) && (loadUserCoupleBuilder_ != null)) {
        return loadUserCoupleBuilder_.getMessageOrBuilder();
      } else {
        if (userInfoCase_ == 4) {
          return (protobuf.vo.OnlineLoadUserCoupleVO) userInfo_;
        }
        return protobuf.vo.OnlineLoadUserCoupleVO.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * 主界面查看搭档
     * </pre>
     *
     * <code>.protobuf.vo.OnlineLoadUserCoupleVO load_user_couple = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        protobuf.vo.OnlineLoadUserCoupleVO, protobuf.vo.OnlineLoadUserCoupleVO.Builder, protobuf.vo.OnlineLoadUserCoupleVOOrBuilder> 
        getLoadUserCoupleFieldBuilder() {
      if (loadUserCoupleBuilder_ == null) {
        if (!(userInfoCase_ == 4)) {
          userInfo_ = protobuf.vo.OnlineLoadUserCoupleVO.getDefaultInstance();
        }
        loadUserCoupleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            protobuf.vo.OnlineLoadUserCoupleVO, protobuf.vo.OnlineLoadUserCoupleVO.Builder, protobuf.vo.OnlineLoadUserCoupleVOOrBuilder>(
                (protobuf.vo.OnlineLoadUserCoupleVO) userInfo_,
                getParentForChildren(),
                isClean());
        userInfo_ = null;
      }
      userInfoCase_ = 4;
      onChanged();;
      return loadUserCoupleBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protobuf.vo.OnlineLoadUserInfoVO)
  }

  // @@protoc_insertion_point(class_scope:protobuf.vo.OnlineLoadUserInfoVO)
  private static final protobuf.vo.OnlineLoadUserInfoVO DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protobuf.vo.OnlineLoadUserInfoVO();
  }

  public static protobuf.vo.OnlineLoadUserInfoVO getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OnlineLoadUserInfoVO>
      PARSER = new com.google.protobuf.AbstractParser<OnlineLoadUserInfoVO>() {
    @java.lang.Override
    public OnlineLoadUserInfoVO parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OnlineLoadUserInfoVO(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OnlineLoadUserInfoVO> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OnlineLoadUserInfoVO> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protobuf.vo.OnlineLoadUserInfoVO getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

