// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OnlineResponseProtocol.proto

package protobuf.vo;

public interface OnlineUserInfoDialogVOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.vo.OnlineUserInfoDialogVO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 用户名称
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * 用户名称
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * 用户等级
   * </pre>
   *
   * <code>uint32 lv = 2;</code>
   * @return The lv.
   */
  int getLv();

  /**
   * <pre>
   * 用户经验
   * </pre>
   *
   * <code>uint32 exp = 3;</code>
   * @return The exp.
   */
  int getExp();

  /**
   * <pre>
   * 用户考级
   * </pre>
   *
   * <code>uint32 cl = 4;</code>
   * @return The cl.
   */
  int getCl();

  /**
   * <pre>
   * 用户所在家族名称及职位
   * </pre>
   *
   * <code>string family = 5;</code>
   * @return The family.
   */
  java.lang.String getFamily();
  /**
   * <pre>
   * 用户所在家族名称及职位
   * </pre>
   *
   * <code>string family = 5;</code>
   * @return The bytes for family.
   */
  com.google.protobuf.ByteString
      getFamilyBytes();

  /**
   * <pre>
   * 用户服装
   * </pre>
   *
   * <code>.protobuf.vo.OnlineClothesVO clothes = 6;</code>
   * @return Whether the clothes field is set.
   */
  boolean hasClothes();
  /**
   * <pre>
   * 用户服装
   * </pre>
   *
   * <code>.protobuf.vo.OnlineClothesVO clothes = 6;</code>
   * @return The clothes.
   */
  protobuf.vo.OnlineClothesVO getClothes();
  /**
   * <pre>
   * 用户服装
   * </pre>
   *
   * <code>.protobuf.vo.OnlineClothesVO clothes = 6;</code>
   */
  protobuf.vo.OnlineClothesVOOrBuilder getClothesOrBuilder();

  /**
   * <pre>
   * 用户冠军数量
   * </pre>
   *
   * <code>uint32 winner_num = 7;</code>
   * @return The winnerNum.
   */
  int getWinnerNum();

  /**
   * <pre>
   * 用户在线曲库总分
   * </pre>
   *
   * <code>uint32 score = 8;</code>
   * @return The score.
   */
  int getScore();

  /**
   * <pre>
   * 用户个性签名
   * </pre>
   *
   * <code>string signature = 9;</code>
   * @return The signature.
   */
  java.lang.String getSignature();
  /**
   * <pre>
   * 用户个性签名
   * </pre>
   *
   * <code>string signature = 9;</code>
   * @return The bytes for signature.
   */
  com.google.protobuf.ByteString
      getSignatureBytes();

  /**
   * <pre>
   * 用户性别
   * </pre>
   *
   * <code>string gender = 10;</code>
   * @return The gender.
   */
  java.lang.String getGender();
  /**
   * <pre>
   * 用户性别
   * </pre>
   *
   * <code>string gender = 10;</code>
   * @return The bytes for gender.
   */
  com.google.protobuf.ByteString
      getGenderBytes();
}
